name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - 'libvore/*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'libvore/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: go build -v ./libvore
    - name: Test
      run: go test -race -coverprofile='coverage.txt' -covermode=atomic -v ./libvore
    - name: Upload coverage to Codecov
      if: success() || failure()
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
